-- IND147206 (export) 
SELECT  ID.APPID, ID.STUDYID, DS.DSDECOD, DM.SEX,DM.SPECIES, BW.USUBJID, BW.BWTESTCD, BW.BWSTRESN, BW.BWSTRESU, TS.TSVAL AS TSSPECIES, TX.TXVAL AS TRTDOSLEVEL
FROM (((((ID INNER JOIN DS ON (DS.STUDYID = ID.STUDYID AND DS.USUBJID = DM.USUBJID ) )
         INNER JOIN TS ON TS.STUDYID = ID.STUDYID)
        INNER JOIN TX ON (TX.STUDYID = ID.STUDYID AND TX.SETCD = DM.SETCD ) )
       INNER JOIN DM ON DM.STUDYID = ID.STUDYID)
      INNER JOIN BW ON (BW.STUDYID = ID.STUDYID AND BW.USUBJID= DM.USUBJID))
WHERE TX.TXPARMCD == "TRTDOS" AND DM.SEX == "M" AND TS.TSPARMCD LIKE '%SPECIES%' AND DS.DSDECOD == "TERMINAL SACRIFICE" AND BW.BWTESTCD == "TERMBW";--0 AND ID.APPID == "IND147206"; 

--- IND147206 (export)nc 
SELECT ID.APPID, ID.STUDYID, DS.DSDECOD, DM.SEX,DM.SPECIES, BW.USUBJID, BW.BWTESTCD, BW.BWSTRESN, BW.BWSTRESU, TS.TSVAL AS TSSPECIES, TX.TXVAL AS TRTDOSLEVEL, TX.TXPARMCD
FROM (((((ID INNER JOIN DS ON (DS.STUDYID = ID.STUDYID AND DS.USUBJID = DM.USUBJID ) )
         INNER JOIN TS ON TS.STUDYID = ID.STUDYID)
        INNER JOIN TX ON (TX.STUDYID = ID.STUDYID AND TX.SETCD = DM.SETCD ) )
       INNER JOIN DM ON DM.STUDYID = ID.STUDYID)
      INNER JOIN BW ON (BW.STUDYID = ID.STUDYID AND BW.USUBJID= DM.USUBJID))
WHERE TX.TXPARMCD == "TCNTRL" AND DM.SEX == "M" AND TS.TSPARMCD LIKE '%SPECIES%' AND DS.DSDECOD == "TERMINAL SACRIFICE" AND BW.BWTESTCD == "TERMBW";




------------------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------------


--- IND147206 (export) 
SELECT  ID.APPID, ID.STUDYID, DS.DSDECOD, DM.SEX,DM.SPECIES, BW.USUBJID, BW.BWTESTCD, BW.BWSTRESN, BW.BWSTRESU, TS.TSVAL AS TSSPECIES, TX.TXVAL AS TRTDOSLEVEL
FROM (((((ID INNER JOIN DS ON (DS.STUDYID = ID.STUDYID AND DS.USUBJID = DM.USUBJID ) )
INNER JOIN TS ON TS.STUDYID = ID.STUDYID)
INNER JOIN TX ON (TX.STUDYID = ID.STUDYID AND TX.SETCD = DM.SETCD ) )
INNER JOIN DM ON DM.STUDYID = ID.STUDYID)
INNER JOIN BW ON (BW.STUDYID = ID.STUDYID AND BW.USUBJID= DM.USUBJID))
WHERE TX.TXPARMCD == "TRTDOS" AND DM.SEX == "M" AND TS.TSPARMCD LIKE '%SPECIES%' AND DS.DSDECOD == "TERMINAL SACRIFICE" AND BW.BWTESTCD == "TERMBW";--0 AND ID.APPID == "IND147206"; 

--- IND147206 (export)nc 
SELECT ID.APPID, ID.STUDYID, DS.DSDECOD, DM.SEX,DM.SPECIES, BW.USUBJID, BW.BWTESTCD, BW.BWSTRESN, BW.BWSTRESU, TS.TSVAL AS TSSPECIES, TX.TXVAL AS TRTDOSLEVEL, TX.TXPARMCD
FROM (((((ID INNER JOIN DS ON (DS.STUDYID = ID.STUDYID AND DS.USUBJID = DM.USUBJID ) )
INNER JOIN TS ON TS.STUDYID = ID.STUDYID)
INNER JOIN TX ON (TX.STUDYID = ID.STUDYID AND TX.SETCD = DM.SETCD ) )
INNER JOIN DM ON DM.STUDYID = ID.STUDYID)
INNER JOIN BW ON (BW.STUDYID = ID.STUDYID AND BW.USUBJID= DM.USUBJID))
WHERE TX.TXPARMCD == "TCNTRL" AND DM.SEX == "M" AND TS.TSPARMCD LIKE '%SPECIES%' AND DS.DSDECOD == "TERMINAL SACRIFICE" AND BW.BWTESTCD == "TERMBW";




SELECT DISTINCT ID.APPID FROM ID;



SELECT  DISTINCT ID.APPID, ID.STUDYID, DS.DSDECOD, TS.TSVAL AS TSSPECIES, BW.BWSTRESN
FROM ((((ID INNER JOIN DS ON DS.STUDYID = ID.STUDYID)
INNER JOIN TS ON TS.STUDYID = ID.STUDYID)
INNER JOIN BW ON BW.STUDYID = ID.STUDYID)
INNER JOIN DM ON DM.STUDYID = ID.STUDYID)
WHERE DM.STUDYID == ID.STUDYID AND TS.TSPARMCD == "SPECIES" AND DS.DSDECOD == "TERMINAL SACRIFICE"AND BW.BWTESTCD == "TERMBW"; -- AND ID.APPID == "BLA125509";
